name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rust-src
      - name: Install avr-gcc, binutils, and libc
        run: sudo apt-get update && sudo apt-get install -y avr-libc binutils-avr gcc-avr
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Show section sizes
        run: avr-size target/avr-attiny2313/release/geiger.elf
